spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

topic:
  hello:
    world: TOPIC_HELLO_WORLD
